# Generated by Django 6.0.3 on 2026-03-15 03:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0006_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ödenen Tutar')),
                ('iyzico_payment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Iyzico Ödeme ID')),
                ('conversation_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True, verbose_name='Benzersiz İşlem Kodu')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('success', 'Başarılı'), ('failed', 'Başarısız')], default='pending', max_length=20, verbose_name='Ödeme Durumu')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Hata Mesajı (Varsa)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='İşlem Tarihi')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='businesses.business', verbose_name='İşletme')),
            ],
            options={
                'verbose_name': 'Abonelik Ödemesi',
                'verbose_name_plural': 'Abonelik Ödemeleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
