# Generated by Django 6.0.3 on 2026-03-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='isletme_logolari/', verbose_name='İşletme Logosu'),
        ),
    ]
