# Generated by Django 6.0.3 on 2026-03-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_business_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='isletme_kapaklari/', verbose_name='Kapak Fotoğrafı'),
        ),
    ]
