# Generated by Django 6.0.3 on 2026-03-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_business_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration_type',
            field=models.CharField(choices=[('minutes', 'Dakika'), ('hours', 'Saat'), ('days', 'Gün'), ('weeks', 'Hafta'), ('months', 'Ay')], default='minutes', max_length=10, verbose_name='Süre Birimi'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Süre'),
        ),
    ]
