# Generated by Django 6.0.3 on 2026-03-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_service_duration_type_alter_service_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Premium İşletme'),
        ),
        migrations.AddField(
            model_name='business',
            name='theme_color',
            field=models.CharField(default='#0d6efd', max_length=7, verbose_name='Tema Rengi (Hex)'),
        ),
    ]
