# Generated by Django 6.0.3 on 2026-03-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_business_is_premium_business_theme_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='location_type',
            field=models.CharField(choices=[('in_store', 'İşletmede (Mekanda)'), ('at_home', 'Müşteri Adresinde (Ev/İşyeri)'), ('online', 'Online (Görüntülü/Telefonda)')], default='in_store', max_length=20, verbose_name='Hizmet Konumu'),
        ),
    ]
