# Generated by Django 6.0.3 on 2026-03-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_service_location_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='customer_address',
            field=models.TextField(blank=True, null=True, verbose_name='Müşteri Adresi (Evde Hizmet)'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='online_app',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Online Uygulama'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='online_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kullanıcı Adı / Link'),
        ),
    ]
