# Generated by Django 6.0.3 on 2026-03-07 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı (Örn: Kuaför, Tamirci)')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='İşletme Adı')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='İşletme Linki')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Şehir')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='İlçe')),
                ('description', models.TextField(blank=True, null=True, verbose_name='İşletme Açıklaması')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='isletme_logolari/', verbose_name='İşletme Logosu')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='isletme_kapaklari/', verbose_name='Kapak Fotoğrafı')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium İşletme')),
                ('theme_color', models.CharField(default='#0d6efd', max_length=7, verbose_name='Tema Rengi (Hex)')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Açık Adres')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='businesses.category', verbose_name='Sektör/Kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyad')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='businesses.business')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Hizmet Adı')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat (TL)')),
                ('location_type', models.CharField(choices=[('in_store', 'İşletmede (Mekanda)'), ('at_home', 'Müşteri Adresinde (Ev/İşyeri)'), ('online', 'Online (Görüntülü/Telefonda)')], default='in_store', max_length=20, verbose_name='Hizmet Konumu')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Süre')),
                ('duration_type', models.CharField(choices=[('minutes', 'Dakika'), ('hours', 'Saat'), ('days', 'Gün'), ('weeks', 'Hafta'), ('months', 'Ay')], default='minutes', max_length=10, verbose_name='Süre Birimi')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='businesses.business')),
            ],
        ),
    ]
