# Generated by Django 6.0.3 on 2026-03-07 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='closing_time',
            field=models.TimeField(default=datetime.time(18, 0), verbose_name='Kapanış Saati'),
        ),
        migrations.AddField(
            model_name='business',
            name='opening_time',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Açılış Saati'),
        ),
    ]
