# Generated by Django 6.0.3 on 2026-03-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_business_closing_time_business_opening_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='theme_color',
            field=models.CharField(default='#D4AF37', max_length=7, verbose_name='Tema Rengi'),
        ),
    ]
