# Generated by Django 6.0.3 on 2026-03-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_business_theme_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='theme_color',
            field=models.CharField(default='#0d6efd', max_length=7, verbose_name='Tema Rengi (Hex)'),
        ),
    ]
