# Generated by Django 6.0.3 on 2026-03-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_alter_business_theme_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='location_type',
        ),
        migrations.AddField(
            model_name='service',
            name='is_at_home',
            field=models.BooleanField(default=False, verbose_name='Müşteri Adresinde Verilir'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_in_store',
            field=models.BooleanField(default=True, verbose_name='İşletmede Verilir'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Online Verilir'),
        ),
    ]
