# Generated by Django 6.0.3 on 2026-03-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False, verbose_name='Dönem Sonunda İptal Edilecek'),
        ),
        migrations.AddField(
            model_name='business',
            name='premium_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Premium Bitiş Tarihi'),
        ),
    ]
