# Generated by Django 6.0.3 on 2026-03-16 22:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_business_cancel_at_period_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Kupon Kodu (Örn: YAZ20)')),
                ('discount_type', models.CharField(choices=[('percentage', 'Yüzdelik İndirim (%)'), ('fixed', 'Sabit İndirim (TL)')], default='percentage', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='İndirim Değeri')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Geçerlilik Başlangıcı')),
                ('valid_until', models.DateTimeField(verbose_name='Geçerlilik Bitişi')),
                ('usage_limit', models.IntegerField(default=0, verbose_name='Kullanım Limiti (0 = Sınırsız)')),
                ('times_used', models.IntegerField(default=0, verbose_name='Kaç Kere Kullanıldı?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='businesses.business')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Personel Adı Soyadı')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Unvanı (Örn: Kıdemli Kuaför)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='personel_fotolari/', verbose_name='Personel Fotoğrafı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='businesses.business')),
            ],
        ),
    ]
