# Generated by Django 6.0.3 on 2026-03-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0008_coupon_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Sistem Onayı (Mavi Tık)'),
        ),
    ]
