# Generated by Django 6.0.3 on 2026-03-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0009_staff_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='staffs',
            field=models.ManyToManyField(blank=True, related_name='services', to='businesses.staff', verbose_name='Bu Hizmeti Verebilen Personeller'),
        ),
    ]
