# Generated by Django 6.0.3 on 2026-03-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0010_service_staffs'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='closed_days',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Kapalı Günler (JS Format)'),
        ),
    ]
