# Generated by Django 6.0.3 on 2026-03-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0011_business_closed_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='google_access_token',
            field=models.TextField(blank=True, null=True, verbose_name='Google Geçici Anahtarı'),
        ),
        migrations.AddField(
            model_name='business',
            name='google_refresh_token',
            field=models.TextField(blank=True, null=True, verbose_name='Google Kalıcı Yenileme Anahtarı'),
        ),
        migrations.AddField(
            model_name='business',
            name='google_token_expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Anahtar Son Kullanma Tarihi'),
        ),
    ]
