# Generated by Django 6.0.3 on 2026-03-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0012_business_google_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='spotify_access_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='spotify_refresh_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='spotify_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
