# Generated by Django 6.0.3 on 2026-03-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0014_businessimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kayıt Tarihi'),
        ),
    ]
