# Generated by Django 6.0.3 on 2026-03-25 23:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0015_business_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Kayıt Tarihi'),
        ),
    ]
