# Generated by Django 6.0.3 on 2026-03-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0016_alter_business_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='campaign_type',
            field=models.CharField(choices=[('none', 'Kampanya Yok'), ('percentage', 'Yüzdelik İndirim (%)'), ('fixed', 'Sabit İndirim (TL)')], default='none', max_length=10, verbose_name='Kampanya Türü'),
        ),
        migrations.AddField(
            model_name='service',
            name='campaign_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='İndirim Değeri'),
        ),
    ]
