# Generated by Django 6.0.3 on 2026-04-01 07:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0017_service_campaign_type_service_campaign_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Gider Başlığı / Açıklaması')),
                ('category', models.CharField(choices=[('kira', 'Kira ve Aidat'), ('fatura', 'Elektrik, Su, Doğalgaz vb. Faturalar'), ('maas', 'Personel Maaş ve Primleri'), ('malzeme', 'Ürün, Malzeme ve Sarf Giderleri'), ('pazarlama', 'Reklam ve Pazarlama (Instagram vb.)'), ('vergi', 'Vergi ve Yasal Kesintiler'), ('diger', 'Diğer Giderler')], max_length=50, verbose_name='Kategori')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar (₺)')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Gider Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='businesses.business')),
            ],
        ),
    ]
