# Generated by Django 6.0.3 on 2026-04-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0018_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('ikram', '☕ Mutfak & İkram (Çay, Kahve, Su vb.)'), ('temizlik', '🧹 Temizlik ve Hijyen Malzemeleri'), ('yemek', '🍔 Personel Yemek ve Günlük Harcırah'), ('ulasim', '🚕 Ulaşım, Kurye ve Kargo Giderleri'), ('tamir', '🔧 Acil Bakım ve Onarım (Tamirat)'), ('malzeme', '📦 Ana Ürün ve Toptan Malzeme Alımı'), ('kira', '🏢 Kira ve Dükkan Aidatı'), ('fatura', '⚡ Faturalar (Elektrik, Su, İnternet)'), ('maas', '💰 Personel Maaş, Avans ve Primleri'), ('pazarlama', '📱 Reklam ve Pazarlama (Sosyal Medya)'), ('vergi', '📜 Vergi, Muhasebe ve Yasal Giderler'), ('diger', '📝 Diğer / Çeşitli Giderler')], max_length=50, verbose_name='Kategori'),
        ),
    ]
