# Generated by Django 6.0.3 on 2026-04-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0019_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='boost_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Boost Bitiş Tarihi'),
        ),
    ]
