# Generated by Django 6.0.3 on 2026-04-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0020_business_boost_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yanıtlanma Tarihi'),
        ),
        migrations.AddField(
            model_name='review',
            name='reply',
            field=models.TextField(blank=True, null=True, verbose_name='İşletme Yanıtı'),
        ),
    ]
