# Generated by Django 6.0.3 on 2026-04-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0021_review_replied_at_review_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif mi (Vitrinde Görünür)'),
        ),
    ]
