# Generated by Django 6.0.3 on 2026-04-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0022_business_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='booking_instruction',
            field=models.TextField(blank=True, help_text='Örn: Lütfen randevu notu kısmına aracınızın marka/modelini yazınız.', null=True, verbose_name='Randevu Talimatı (Müşteriye Gösterilir)'),
        ),
    ]
