# Generated by Django 6.0.3 on 2026-05-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0023_service_booking_instruction'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Engellenen Telefon')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Engelleme Sebebi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Global Kara Liste',
                'verbose_name_plural': 'Global Kara Liste',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Engellendi mi?'),
        ),
    ]
