# Generated by Django 5.2.13 on 2026-05-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0027_alter_auditlog_id_alter_business_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Hayır seçilirse kupon vitrinde listelenmez, sadece kodu bilenler kullanabilir.', verbose_name='Vitrinde Görünsün mü?'),
        ),
    ]
