# Generated by Django 5.2.13 on 2026-05-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0028_coupon_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=5, verbose_name='Komisyon Oranı (%)'),
        ),
        migrations.AddField(
            model_name='business',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='business',
            name='iyzico_sub_merchant_key',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Iyzico Alt Üye İşyeri Anahtarı'),
        ),
        migrations.AddField(
            model_name='business',
            name='sub_merchant_type',
            field=models.CharField(default='PERSONAL', max_length=20, verbose_name='İşletme Türü'),
        ),
        migrations.AddField(
            model_name='business',
            name='tax_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Vergi Numarası / TC No'),
        ),
        migrations.AddField(
            model_name='business',
            name='tax_office',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vergi Dairesi'),
        ),
    ]
