# Generated by Django 5.2.13 on 2026-05-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0029_business_commission_rate_business_iban_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='iban',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='business',
            name='tax_number',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Vergi Numarası / TC No'),
        ),
        migrations.AlterField(
            model_name='business',
            name='tax_office',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Vergi Dairesi'),
        ),
    ]
