# Generated by Django 5.2.13 on 2026-05-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0030_alter_business_iban_alter_business_tax_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Enlem (Latitude)'),
        ),
        migrations.AddField(
            model_name='business',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Boylam (Longitude)'),
        ),
    ]
