# Generated by Django 5.2.13 on 2026-05-21 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0031_business_latitude_business_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('ikram', 'Mutfak & İkram (Çay, Kahve, Su vb.)'), ('temizlik', 'Temizlik ve Hijyen Malzemeleri'), ('yemek', 'Personel Yemek ve Günlük Harcırah'), ('ulasim', 'Ulaşım, Kurye ve Kargo Giderleri'), ('tamir', 'Acil Bakım ve Onarım (Tamirat)'), ('malzeme', 'Ana Ürün ve Toptan Malzeme Alımı'), ('kira', 'Kira ve Dükkan Aidatı'), ('fatura', 'Faturalar (Elektrik, Su, İnternet)'), ('maas', 'Personel Maaş, Avans ve Primleri'), ('pazarlama', 'Reklam ve Pazarlama (Sosyal Medya)'), ('vergi', 'Vergi, Muhasebe ve Yasal Giderler'), ('diger', 'Diğer / Çeşitli Giderler')], max_length=50, verbose_name='Kategori'),
        ),
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Gider Başlığı')),
                ('expense_type', models.CharField(choices=[('rent', 'Kira ve Dükkan Aidatı'), ('salary', 'Personel Maaşları'), ('meal', 'Personel Yemek Ücreti'), ('other', 'Diğer Düzenli Giderler')], max_length=20, verbose_name='Gider Türü')),
                ('is_per_staff', models.BooleanField(default=False, verbose_name='Çalışan Başına mı Hesaplasın?')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar (₺)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_expenses', to='businesses.business')),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='auto_generated_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_expenses', to='businesses.recurringexpense'),
        ),
    ]
