# Generated by Django 5.2.13 on 2026-05-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0032_alter_expense_category_recurringexpense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating_cleanliness',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='Temizlik & Hijyen'),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_hospitality',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='Müşteri Karşılama'),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_quality',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='Hizmet Kalitesi'),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_value',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='Fiyat/Performans'),
        ),
    ]
