# Generated by Django 5.2.13 on 2026-05-21 19:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0033_review_rating_cleanliness_review_rating_hospitality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Gelir Başlığı / Açıklaması')),
                ('category', models.CharField(choices=[('elden', 'Elden / Doğrudan Müşteri Hasılatı'), ('urun', 'Ekstra Ürün Satışı Hasılatı'), ('diger', 'Diğer Gelirler / Çeşitli Hasılat')], max_length=50, verbose_name='Kategori')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar (₺)')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Gelir Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='businesses.business')),
            ],
        ),
    ]
