# Generated by Django 5.2.13 on 2026-05-21 21:43

import uuid
from django.db import migrations, models

def gen_uuid(apps, schema_editor):
    Staff = apps.get_model('businesses', 'Staff')
    for row in Staff.objects.all():
        row.secure_token = uuid.uuid4()
        row.save(update_fields=['secure_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0034_income'),
    ]

    operations = [
        # 1. Add field as null=True without unique=True
        migrations.AddField(
            model_name='staff',
            name='secure_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        # 2. Populate existing rows with unique UUIDs
        migrations.RunPython(gen_uuid, elidable=True),
        # 3. Alter field to be unique=True, editable=False
        migrations.AlterField(
            model_name='staff',
            name='secure_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
