# Generated by Django 5.2.13 on 2026-06-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0035_staff_secure_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='spotify_access_token',
            field=models.TextField(blank=True, null=True, verbose_name='Spotify Erişim Anahtarı'),
        ),
        migrations.AlterField(
            model_name='business',
            name='spotify_refresh_token',
            field=models.TextField(blank=True, null=True, verbose_name='Spotify Yenileme Anahtarı'),
        ),
    ]
