# Generated by Django 5.2.13 on 2026-06-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0036_alter_business_spotify_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Şehir'),
        ),
        migrations.AlterField(
            model_name='business',
            name='district',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='İlçe'),
        ),
        migrations.AlterField(
            model_name='business',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Aktif mi (Vitrinde Görünür)'),
        ),
        migrations.AlterField(
            model_name='business',
            name='is_premium',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Premium İşletme'),
        ),
    ]
