# Generated by Django 6.0.3 on 2026-08-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0037_alter_business_city_alter_business_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='ad_badge_text',
            field=models.CharField(blank=True, default='SPONSORLU', max_length=50, null=True, verbose_name='Reklam Rozeti'),
        ),
        migrations.AddField(
            model_name='business',
            name='ad_clicks',
            field=models.PositiveIntegerField(default=0, verbose_name='Reklam Tıklanma Sayısı'),
        ),
        migrations.AddField(
            model_name='business',
            name='ad_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reklam Panosu Bitiş Tarihi'),
        ),
        migrations.AddField(
            model_name='business',
            name='ad_impressions',
            field=models.PositiveIntegerField(default=0, verbose_name='Reklam Gösterim Sayısı'),
        ),
        migrations.AddField(
            model_name='business',
            name='ad_slogan',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Reklam Sloganı'),
        ),
    ]
