"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# .env dosyasını sisteme yüklüyoruz
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-eqvol@2f&7**)6izql(h=j_na(%1nb-+%2%4gib6vlqd*1shi1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*'] # Geliştirme aşamasında her yerden erişime izin ver


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'accounts',      # Üyelik, giriş, çıkış
    'businesses',    # Dükkan, hizmetler, müşteriler
    'appointments',  # Randevular, takvim, saatler
    'payments',      # Ödeme İşlemleri
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'businesses.middleware.PremiumStatusMiddleware', # Müşteri Premium Kontrolü
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'tr'
TIME_ZONE = 'Europe/Istanbul'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
# YENİ EKLENDİ: Ana dizindeki static klasörünü tanıması için
STATICFILES_DIRS = [BASE_DIR / "static"]

# Medya Dosyaları (Kullanıcı logoları, fotolar vb.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# --- GERÇEK MAİL AYARLARI ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
# YENİ EKLENDİ: Maillerin spam klasörüne düşmemesi ve views.py hatasını önlemek için
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Şifre sıfırlama linki geçerlilik süresi (Saniye cinsinden). 7200 saniye = 2 Saat
PASSWORD_RESET_TIMEOUT = 7200

# --- CELERY & REDIS AYARLARI ---
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'


# --- IYZICO ÖDEME AYARLARI ---
IYZICO_API_KEY = os.getenv('IYZICO_API_KEY')
IYZICO_SECRET_KEY = os.getenv('IYZICO_SECRET_KEY')
IYZICO_BASE_URL = os.getenv('IYZICO_BASE_URL')