"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# .env dosyasını sisteme yüklüyoruz
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# SECURITY WARNING: Sadece .env dosyasından çeker, bulamazsa anında sistemi durdurur (En güvenlisi)
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: Sadece .env'de True yazıyorsa True olur.
DEBUG = os.getenv('DJANGO_DEBUG') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')


# --- PRODUCTION SECURITY SETTINGS ---
if not DEBUG:
    # 🛡️ Güvenlik Başlıkları (Security Headers)
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000 # 1 Yıl
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True # HTTPS zorunluluğu

    # 🍪 Çerez Güvenliği (Cookie Security)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'
else:
    # Geliştirme ortamında kolaylık
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'


# Application definition
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'accounts',      # Üyelik, giriş, çıkış
    'businesses',    # Dükkan, hizmetler, müşteriler
    'appointments',  # Randevular, takvim, saatler
    'payments',      # Ödeme İşlemleri
    'pos',           # POS(Adisyon) Sistemi
    'debug_toolbar', # Debug Toolbar
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

INTERNAL_IPS = [
    "127.0.0.1",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'trandevu_db'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

JAZZMIN_SETTINGS = {
    "site_title": "KobiRandevu Admin",
    "site_header": "KobiRandevu",
    "site_brand": "Sistem Yönetimi",
    "welcome_sign": "KobiRandevu Yönetim Merkezine Hoş Geldiniz, Patron!",
    "copyright": "KobiRandevu Inc.",
    "search_model": ["businesses.Business", "auth.User"],
    "show_ui_builder": False,

    # --- Görsel İyileştirmeler ---
    "changeform_format": "single",
    "language_chooser": False,
    "related_modal_active": False,

    # --- Sol Menü İkonları (Uygulamalarına Özel) ---
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user-shield",
        "auth.Group": "fas fa-users",
        "appointments.Appointment": "fas fa-calendar-alt",
        "businesses.Business": "fas fa-building",
        "businesses.Category": "fas fa-tags",
        "businesses.Service": "fas fa-concierge-bell",
        "businesses.Staff": "fas fa-user-tie",
        "businesses.Customer": "fas fa-user-friends",
        "businesses.Coupon": "fas fa-ticket-alt",
        "businesses.Review": "fas fa-star",
        "pos.Adisyon": "fas fa-receipt",
        "pos.Product": "fas fa-box-open",
    },
    "hide_apps": [],
    "custom_css": "css/premium_admin.css",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "theme": "slate",
    "dark_mode_theme": "slate",
    "actions_sticky_top": False,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

# Internationalization
LANGUAGE_CODE = 'tr'
TIME_ZONE = 'Europe/Istanbul'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Medya Dosyaları (Kullanıcı logoları, fotolar vb.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# --- GERÇEK MAİL AYARLARI ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# --- WEB SITE ALAN ADI AYARI ---
SITE_URL = os.getenv('SITE_URL', 'http://127.0.0.1:8000')

# --- GOOGLE CALENDAR API AYARLARI ---
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET')

# Şifre sıfırlama linki geçerlilik süresi
PASSWORD_RESET_TIMEOUT = 7200

# --- CELERY & REDIS AYARLARI ---
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

# --- CACHE AYARLARI ---
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': 'redis://localhost:6379/1',
    }
}

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'randevu-hatirlaticilari-kontrol-et': {
        'task': 'appointments.tasks.send_24_hour_reminders',
        'schedule': crontab(minute=0),
    },
    'premium-surelerini-kontrol-et': {
        'task': 'appointments.tasks.check_all_premium_statuses_task',
        'schedule': crontab(hour=0, minute=1),
    },
    'gunluk-sabah-ajandasi': {
        'task': 'appointments.tasks.send_daily_morning_agenda_task',
        'schedule': crontab(hour=8, minute=0),
    },
    'odeme-bekleyen-randevulari-temizle': {
        'task': 'appointments.tasks.cleanup_stale_payment_pending_task',
        'schedule': crontab(minute='*/10'),
    },
}

# --- GÜVENLİK VE ŞİFRELEME AYARLARI ---
FIELD_ENCRYPTION_KEY = os.getenv('FIELD_ENCRYPTION_KEY')

# --- IYZICO ÖDEME AYARLARI ---
IYZICO_API_KEY = os.getenv('IYZICO_API_KEY')
IYZICO_SECRET_KEY = os.getenv('IYZICO_SECRET_KEY')
IYZICO_BASE_URL = os.getenv('IYZICO_BASE_URL')

# --- SPOTIFY API AYARLARI ---
SPOTIFY_CLIENT_ID = os.getenv('SPOTIFY_CLIENT_ID')
SPOTIFY_CLIENT_SECRET = os.getenv('SPOTIFY_CLIENT_SECRET')

# --- GİRİŞ VE YÖNLENDİRME AYARLARI ---
LOGIN_URL = '/hesap/giris/'
LOGIN_REDIRECT_URL = 'isletme_sec'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
