# Generated by Django 6.0.3 on 2026-03-31 15:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0007_alter_appointment_status'),
        ('businesses', '0017_service_campaign_type_service_campaign_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adisyon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Açık (İşlem Devam Ediyor)'), ('closed', 'Kapatıldı (Ödendi)')], default='open', max_length=20, verbose_name='Durum')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Nakit'), ('cc', 'Kredi Kartı (Fiziksel POS)'), ('online', 'Sadece Online Ödendi')], max_length=20, null=True, verbose_name='Ekstra Ödeme Yöntemi')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adisyon', to='appointments.appointment', verbose_name='Bağlı Randevu')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adisyonlar', to='businesses.business')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ürün / Ekstra Hizmet Adı')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Birim Fiyat (₺)')),
                ('stock', models.IntegerField(blank=True, default=0, null=True, verbose_name='Stok (İsteğe Bağlı)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Satışta mı?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='businesses.business')),
            ],
        ),
        migrations.CreateModel(
            name='AdisyonItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Adet')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Birim Fiyat')),
                ('adisyon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.adisyon')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.product', verbose_name='Ürün')),
            ],
        ),
    ]
