# Generated by Django 6.0.3 on 2026-03-31 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0017_service_campaign_type_service_campaign_value'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adisyonitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='businesses.service', verbose_name='Ekstra Hizmet'),
        ),
        migrations.AlterField(
            model_name='adisyonitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.product', verbose_name='Ürün'),
        ),
    ]
