# Generated by Django 6.0.3 on 2026-04-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_adisyonitem_service_alter_adisyonitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='adisyon',
            name='fis_no',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='İşletme Fiş No'),
        ),
    ]
