# Generated by Django 6.0.3 on 2026-04-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_adisyon_fis_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='adisyonitem',
            name='total_price_cache',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
