# Generated by Django 6.0.3 on 2026-04-07 19:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_adisyonitem_total_price_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='adisyon',
            name='security_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
