# Generated by Django 6.0.3 on 2026-04-07 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_adisyon_security_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adisyon',
            name='security_token',
        ),
    ]
