# Generated by Django 6.0.3 on 2026-04-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_remove_adisyon_security_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adisyon',
            name='closed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='adisyon',
            name='status',
            field=models.CharField(choices=[('open', 'Açık (İşlem Devam Ediyor)'), ('closed', 'Kapatıldı (Ödendi)')], db_index=True, default='open', max_length=20, verbose_name='Durum'),
        ),
    ]
