# Generated by Django 6.0.3 on 2026-03-07 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Randevu Tarihi ve Saati')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('confirmed', 'Onaylandı'), ('cancelled', 'İptal Edildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Randevu Notları')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_address', models.TextField(blank=True, null=True, verbose_name='Müşteri Adresi (Evde Hizmet)')),
                ('online_app', models.CharField(blank=True, max_length=50, null=True, verbose_name='Online Uygulama')),
                ('online_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kullanıcı Adı / Link')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='businesses.business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='businesses.customer')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='businesses.service', verbose_name='Hizmet')),
            ],
        ),
    ]
