# Generated by Django 6.0.3 on 2026-03-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='customer_note',
            field=models.TextField(blank=True, null=True, verbose_name='Müşteri Notu'),
        ),
    ]
