# Generated by Django 6.0.3 on 2026-03-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_customer_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='chosen_location',
            field=models.CharField(choices=[('in_store', 'İşletmede'), ('at_home', 'Müşteri Adresinde'), ('online', 'Online Görüşme')], default='in_store', max_length=20, verbose_name='Seçilen Konum'),
        ),
    ]
