# Generated by Django 6.0.3 on 2026-03-14 01:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_chosen_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_reviewed',
            field=models.BooleanField(default=False, verbose_name='Değerlendirildi mi?'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='review_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
