# Generated by Django 6.0.3 on 2026-03-16 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_is_reviewed_appointment_review_token'),
        ('businesses', '0008_coupon_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='coupon_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='businesses.coupon', verbose_name='Kullanılan Kupon'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='final_service_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='İşletmeye Ödenecek Net Tutar'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Online Ödeme Başarılı mı?'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='iyzico_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İyzico İşlem Numarası'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='platform_fee_paid',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=6, verbose_name='T-Randevu İşlem Bedeli'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='businesses.staff', verbose_name='Personel'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='total_online_charged',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10, verbose_name='Online Tahsil Edilen Tutar'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='İşletme/Randevu Notları'),
        ),
    ]
