# Generated by Django 6.0.3 on 2026-03-17 16:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_coupon_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancel_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Bekliyor'), ('confirmed', 'Onaylandı'), ('cancelled', 'İptal Edildi'), ('completed', 'Tamamlandı')], default='pending', max_length=20, verbose_name='Durum'),
        ),
    ]
