# Generated by Django 6.0.3 on 2026-03-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_cancel_token_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Bekliyor'), ('confirmed', 'Onaylandı'), ('cancelled', 'İptal Edildi (İşletme)'), ('customer_cancelled', 'İptal Edildi (Müşteri)'), ('completed', 'Tamamlandı')], default='pending', max_length=20, verbose_name='Durum'),
        ),
    ]
