# Generated by Django 6.0.3 on 2026-04-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Hatırlatıcı Gönderildi mi?'),
        ),
    ]
