# Generated by Django 6.0.3 on 2026-04-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_appointment_is_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_business_modified',
            field=models.BooleanField(default=False, verbose_name='İşletme Tarafından Zorla Değiştirildi'),
        ),
    ]
