# Generated by Django 6.0.3 on 2026-04-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_appointment_is_business_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_time',
            field=models.DateTimeField(db_index=True, verbose_name='Randevu Tarihi ve Saati'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Bekliyor'), ('confirmed', 'Onaylandı'), ('cancelled', 'İptal Edildi (İşletme)'), ('customer_cancelled', 'İptal Edildi (Müşteri)'), ('completed', 'Tamamlandı')], db_index=True, default='pending', max_length=20, verbose_name='Durum'),
        ),
    ]
