# Generated by Django 6.0.3 on 2026-05-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_alter_appointment_date_time_alter_appointment_status'),
        ('businesses', '0024_globalblacklist_customer_is_blocked'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['cancelled', 'customer_cancelled', 'payment_pending']), _negated=True), fields=('staff', 'date_time'), name='unique_active_appointment_for_staff'),
        ),
    ]
