# Generated by Django 6.0.3 on 2026-05-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_appointment_unique_active_appointment_for_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('payment_pending', 'Ödeme Bekleniyor'), ('pending', 'Bekliyor'), ('confirmed', 'Onaylandı'), ('cancelled', 'İptal Edildi (İşletme)'), ('customer_cancelled', 'İptal Edildi (Müşteri)'), ('completed', 'Tamamlandı')], db_index=True, default='pending', max_length=20, verbose_name='Durum'),
        ),
    ]
