import re

wizard_path = "businesses/templates/businesses/booking_wizard.html"
isletme_detay_path = "businesses/templates/businesses/isletme_detay.html"

# Fix Booking Wizard
with open(wizard_path, "r", encoding="utf-8") as f:
    content = f.read()

# 1. Remove font imports and font-family rules
content = re.sub(r'<link href="https://fonts\.googleapis\.com/css2\?family=(Inter|Syne).*?>\n?', '', content)
content = re.sub(r'font-family:.*?;', '', content)
content = re.sub(r'h1, h2, h3, h4 \{[\s\S]*?\}', '', content)

# 2. Fix the date generation bug (HTML comment inside div)
content = content.replace("<!-- Dates will be generated by JS -->", "")

# 3. Add a clear "Geri Dön" button next to "Devam Et"
btn_continue = '<button id="btnContinue" class="btn-primary-custom mt-6" disabled onclick="nextStep()">Devam Et</button>'
new_btns = """<div class="flex gap-2 mt-6">
                    <button id="btnBackMain" class="btn-primary-custom !bg-[var(--bg-hover)] !text-[var(--text-main)] border border-[var(--border-dim)] !w-1/3 hidden" onclick="goBack()">Geri</button>
                    <button id="btnContinue" class="btn-primary-custom !w-full transition-all" disabled onclick="nextStep()">Devam Et</button>
                </div>"""
content = content.replace(btn_continue, new_btns)

# 4. Update JS to show/hide the back button
js_update_cart = """
        if (currentStep > 1) {
            document.getElementById('btnBackMain').classList.remove('hidden');
            document.getElementById('btnContinue').classList.remove('!w-full');
            document.getElementById('btnContinue').classList.add('!w-2/3');
        } else {
            document.getElementById('btnBackMain').classList.add('hidden');
            document.getElementById('btnContinue').classList.add('!w-full');
            document.getElementById('btnContinue').classList.remove('!w-2/3');
        }
"""
# Insert inside updateCart() at the bottom
content = content.replace("btn.innerText = \"Devam Et\";\n        }", "btn.innerText = \"Devam Et\";\n        }\n" + js_update_cart)

with open(wizard_path, "w", encoding="utf-8") as f:
    f.write(content)

# Fix Isletme Detay
with open(isletme_detay_path, "r", encoding="utf-8") as f:
    content = f.read()

# Remove font imports and font-family overrides completely
content = re.sub(r'<link href="https://fonts\.googleapis\.com/css2\?family=(Syne|Inter|DM\+Sans).*?>\n?', '', content)
content = re.sub(r'--font-display:.*?;', '', content)
content = re.sub(r'--font-body:.*?;', '', content)

with open(isletme_detay_path, "w", encoding="utf-8") as f:
    f.write(content)

print("Patch applied.")
